# This file was generated by GoReleaser. DO NOT EDIT.
class Table < Formula
  desc "Print CSV and JSON documents in a table format."
  homepage "https://github.com/elwin/table"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/elwin/table/releases/download/v1.0.1/table_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "be8edb2de7d0ae728750466c08923419c7a9aacd9922af5677dee8bcdffd90d4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/elwin/table/releases/download/v1.0.1/table_1.0.1_Linux_x86_64.tar.gz"
      sha256 "26ab35be4c352a7e1735a6b5313907a308e74e563dc48c48b7024d774573a2a8"
    end
  end

  def install
    bin.install "table"
  end
end
